name: Update GitHub Pages Cache

on:
  push:
    branches:
      - main  # или ваша основная ветка (например, gh-pages)

jobs:
  update_cache:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate new script version
      run: |
        # Получаем текущую временную метку
        TIMESTAMP=$(date +%s)

        # Переименовываем файл index.js с уникальным именем
        mv index.js index-${TIMESTAMP}.js

        # Настроим Git для коммита
        git config --global user.name "AlexxxPetrov"
        git config --global user.email "twisted.transisitor.2019@gmail.com"

        # Добавляем новый файл в репозиторий
        git add index-${TIMESTAMP}.js
        git commit -m "Update script to version ${TIMESTAMP}"

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Используем автоматический токен для пуша
      run: |
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
